name = "nexus-a1"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]


# ⭐ YAHAN BHI ADD KARO (For better performance)
[env.production]
vars = { ENVIRONMENT = "production" }

[[kv_namespaces]]
binding = "KV"
id = "7f3a894d6cb041b3a7c25546f8714342"

[[services]]
binding = "NEXUS_MCP_SERVER"
service = "nexus-mcp-server"

[[kv_namespaces]]
binding = "NEXUS_KV"
id = "67a179e277924b17bf63b28b61ffd546"

[[d1_databases]]
binding = "DB"
database_name = "nexus_users"
database_id = "80563f0c-f9f7-4af4-aa12-941a093cb88e"

[vars]
NEXUS_INTERNAL_AUTH_SECRET = "N7vQ2xL9mK4pR8zT6wY3cH5jF1sD0aB8uE6nG9qW2rX7kP4tM5vZ8yC3fJ6hL1"

[[vectorize]]
binding = "VECTOR"
index_name = "captain-cool-index"

[ai]
binding = "AI"

[[migrations]]
tag = "v1"

